### ISSUE TITLE
Use isinstance() for type checks

### ISSUE THREAD

**Issue by 0az** [ucsd-ets/dsc10-fa18#3]
One way to make the type check more explicit and to make the error message more helpful is to replace the `type(obj) == Type` calls with explicit `isinstance` calls.

```Python
>>> obj = object()
>>> type(obj) == obj
False
>>> isinstance(obj, obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

**Comment by afraenkel** [comment]
Thanks for your input! 

Part of this is that many of the tests are templated / built from old code / tests. Course staff only has so much time to upgrade legacy code -- and new tests (not templated from old) do use isinstance where appropriate.

I'd note that isinstance is not all better though: students know the `type` function and so can figure out what the test-code is actually testing -- and can debug appropriately by running the test line in the notebook. So I do not think it makes the error message much more helpful if you don't know `isinstance`. You're example is a little odd, because with a well-written test, neither isinstance nor type would return an error.  A test would presumably look like `isinstance(obj, object)` which returns True.
[[EDIT: I understand the example now -- for the case student's overwrite the type names -- got it!]]

The fact that `isinstance` handles inheritance appropriately is nice however -- and if you'd like to make changes to tests to use isinstance in the case of strings/ints/floats (see for example: Projects/project_college_scorecard/tests/q1_1.py), please do! We could use the help :)
